version: '3.8'

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  prometheus_data:
  grafana_data:

services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks: [backend]
    depends_on:
      frontend:
        condition: service_started # ou service_healthy si vous ajoutez un healthcheck au frontend
      web:
        condition: service_healthy # Dépend de la santé du service web
      grafana:
        condition: service_healthy # Dépend de la santé du service grafana
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

  grafana:
    image: grafana/grafana:latest
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    networks: [backend]
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:3000/-/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks: [backend]

  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    command: >
      sh -c "
        python manage.py migrate &&
        gunicorn server_config.wsgi:application --bind 0.0.0.0:8000
      "
    networks: [backend]
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    healthcheck: 
      test: ["CMD-SHELL", "wget --spider http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    command: >
      sh -c "poetry run celery -A server_config worker --loglevel=info"
    depends_on:
      - web
      - rabbitmq
    networks: [backend]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "4173"
    ports:
      - "4173:4173"
    networks: [backend]

