# prometheus.yml
global:
  scrape_interval: 15s # fréquence de collecte par défaut
  evaluation_interval: 15s # fréquence d'évaluation des règles

scrape_configs:
  - job_name: django
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
